name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0' # Adjust version as needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the Angular app
    - name: Build the Angular app
      run: npm run build -- --output-path=dist --base-href="/cms-application/"

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
